### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by rahlk** [juhidesai/x9115baymax#1]
- [ ] X = 136 is too large. x=1 is the ideal solution. This may be because of:
  1. Number of iterations.
  2. Neighborhood function.
- [ ] Can you print the energy after every 25 repeats in your outputs please.

**Comment by juhidesai** [comment]
Hi Rahul,

We increased the number of iterations from 1000 to 50000 and got the new result as 1. I'll update the same in the README as well as the code

<img width="414" alt="new_sa" src="https://cloud.githubusercontent.com/assets/9724890/10175663/4453bf2e-66be-11e5-88b6-29a27c7b0fc5.PNG">
